name: ci

on: pull_request
jobs:
    test:
        runs-on: ubunto-latest

        steps:
            - name: primeira CI nossa
              run: echo hello

            - name: o que tem aqui
              run: echo $(ls)  